# Generated by Django 4.1 on 2022-09-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_booking_departments_doctors_delete_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
